### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ayalash**
* Move to GitHub Actions (from Travis CI)
* Use `pyproject.toml` for project metadata

### CODE REVIEW

**Review by vmalloc — APPROVED** [review]

**Comment by vmalloc** [comment]
Thanks!

**Comment by pierreluctg** [comment]
@ayalash would it be possible to make a new release including this change?

The fact that `python_requires` in previous releases is not PEP 440 compatible is a blocker for us now.
https://github.com/getslash/slash-step/blob/ec7568c1ea472e000fe5b29d3d0458c4003239c2/setup.py#L8

Thank you

**Comment by ayalash** [comment]
@pierreluctg I've just released version 1.1.0

**Comment by ayalash** [comment]
@pierreluctg I've also just released 1.2.0 which adds support for python 3.12 and remove support for 3.7

**Comment by pierreluctg** [comment]
Thank you @ayalash

**Pull request merged**
